# Generated by Django 4.2.7 on 2023-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=20),
        ),
    ]
